services:
  maria:
    image: mariadb
    container_name: glpi_db
    stdin_open: false
    tty: false
    hostname: glpi_db
    domainname: routerology.lab
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootsecret
      MARIADB_USER: somedude
      MARIADB_PASSWORD: somesecret
      MARIADB_DATABASE: somebase
    init: false
    privileged: false
    networks:
      - default

  glpi:
    image: routerology/glpi
    container_name: glpi_app
    stdin_open: true
    tty: true
    hostname: glpi_app
    domainname: routerology.lab
    restart: unless-stopped
    init: true
    privileged: false
    ports:
      - "8080:80"
    networks:
      - default
    volumes: 
      - type: bind
        source: ./logs
        target: /var/log/apache2
      - type: bind
        source: ./logs/glpi
        target: /var/log/glpi
      - type: bind
        source: ./server_config/httpd.conf
        target: /etc/apache2/httpd.conf
      - type: bind
        source: ./server_config/php.ini
        target: /etc/php83/php.ini
      - type: bind
        source: ./glpi_config
        target: /etc/glpi
      - type: bind
        source: ./glpi_var
        target: /var/lib/glpi
      - type: bind
        source: ./glpi_marketplace
        target: /var/www/glpi/marketplace
      - type: bind
        source: ./glpi_plugins
        target: /var/www/glpi/plugins

networks:
  default:
    name: custom_bridge
    external: true

