services:
  maria:
    image: mariadb
    container_name: glpi_db
    stdin_open: false
    tty: false
    hostname: glpi_db
    domainname: routerology.lab
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootsecret
      MARIADB_USER: somedude
      MARIADB_PASSWORD: somesecret
      MARIADB_DATABASE: somebase
    init: false
    privileged: false
    networks:
      - default

  glpi:
    image: routerology/glpi
    container_name: glpi_app
    stdin_open: true
    tty: true
    hostname: glpi_app
    domainname: routerology.lab
    restart: unless-stopped
    init: true
    privileged: false
    ports:
      - "8080:80"
    networks:
      - default

networks:
  default:
    name: custom_bridge
    external: true
