services:
  maria:
    image: mariadb
    container_name: glpi_db
    stdin_open: false
    tty: false
    hostname: glpi_db
    domainname: packets.lab
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: glpi_root_pass
      MARIADB_USER: glpi_db_user
      MARIADB_PASSWORD: glpi_db_pass
      MARIADB_DATABASE: glpi_db
    init: false
    privileged: false
    networks:
      glpi_net:
  glpi:
    image: routerology/glpi
    container_name: glpi_app
    stdin_open: true
    tty: true
    hostname: glpi_app
    domainname: packets.lab
    restart: unless-stopped
    environment:
      test_var1: test_value
    init: true
    privileged: false
    networks:
      glpi_net:
    volumes: 
      - type: bind
        source: ./www
        target: /var/www/glpi
      - type: bind
        source: ./log
        target: /var/log/apache2
      - type: bind
        source: ./log/glpi
        target: /var/log/glpi
      - type: bind
        source: ./httpd_conf/httpd.conf
        target: /etc/apache2/httpd.conf
      - type: bind
        source: ./php_ini/php.ini
        target: /etc/php81/php.ini
      - type: bind
        source: ./glpi_config
        target: /etc/glpi
      - type: bind
        source: ./glpi_var
        target: /var/lib/glpi
      - type: bind
        source: ./downstream.php
        target: /var/www/glpi/inc/downstream.php

networks:
  glpi_net:
    name: glpi_net
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
          ip_range: 192.168.200.0/24
          gateway: 192.168.200.1
          aux_addresses:
            host1: 192.168.200.2
            host2: 192.168.200.3

