services:
  maria:
    image: mariadb
    container_name: glpi_db
    stdin_open: false
    tty: false
    hostname: glpi_db
    domainname: routerology.ro
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootsecret
      MARIADB_USER: somedude
      MARIADB_PASSWORD: somesecret
      MARIADB_DATABASE: somebase
    init: false
    privileged: false
    networks:
      glpi_net:

  glpi:
    image: routerology/glpi
    container_name: glpi
    stdin_open: true
    tty: true
    hostname: glpi
    domainname: routerology.ro
    restart: unless-stopped
    environment:
      test_var1: test_value
    init: true
    privileged: false
    networks:
      glpi_net:

networks:
  glpi_net:
    name: glpi_net
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.200.0/24
          ip_range: 192.168.200.0/24
          gateway: 192.168.200.1
          aux_addresses:
            host1: 192.168.200.2
            host2: 192.168.200.3

